"""SCNet 容器 API Python SDK（同步 + 异步）。

支撑容器创建、状态查询（执行状态）、批量执行脚本与删除，
接口与字段严格对齐 api/scnet 目录下的官方文档。

- 同步客户端：:class:`ScnetClient`
- 异步客户端：:class:`AsyncScnetClient`（asyncio，适配 FastAPI 等异步服务）

配置分两层：类库系统态（包内 `defaults.yaml`）与用户态（本地 YAML / 环境变量），
详见 :mod:`scnet_sdk.config`。
"""
from .aclient import AsyncContainerHandle, AsyncScnetClient
from .auth import (
    DEFAULT_CENTER_URL,
    DEFAULT_TOKEN_URL,
    ClusterToken,
    ScnetCredentials,
    build_sign_message,
    build_signature,
    build_token_headers,
    fetch_center,
    fetch_center_async,
    fetch_tokens,
    fetch_tokens_async,
    normalize_ai_url,
    obtain_credentials,
    obtain_credentials_async,
    pick_ai_urls,
    resolve_ai_url,
    select_cluster,
)
from .base import (
    WAIT_PENDING,
    WAIT_READY,
    WAIT_TERMINAL,
    ScnetClientBase,
    build_create_payload,
    build_script_body,
    normalize_ids,
    parse_container_info,
    parse_created_id,
    parse_resource_limits,
    wait_decision,
)
from .client import ContainerHandle, ScnetClient
from .config import (
    CODE_DEFAULTS,
    CONFIG_ENV_VAR,
    DEFAULT_CONFIG_NAMES,
    ENV_OVERRIDES,
    ENV_PREFIX,
    PACKAGED_DEFAULTS_NAME,
    Endpoints,
    Paths,
    ScnetConfig,
    StatusSets,
    Timeouts,
    deep_merge,
    env_layer,
    load_yaml,
    packaged_defaults,
    resolve_config_path,
    search_paths,
)
from .errors import (
    ERROR_MESSAGES,
    ScnetApiError,
    ScnetAuthError,
    ScnetConfigError,
    ScnetError,
    ScnetResponseError,
    ScnetStateError,
    ScnetTimeoutError,
    ScnetTransportError,
    ScnetValidationError,
    describe_code,
)
from .models import (
    ACCELERATOR_TYPES,
    DEFAULT_RUNNING_STATUSES,
    DEFAULT_TERMINAL_STATUSES,
    MOUNT_TYPES,
    PROTOCOL_TYPES,
    SCRIPT_ACTION_SCOPES,
    TASK_TYPES,
    ContainerInfo,
    ContainerSpec,
    MountInfo,
    PortInfo,
    ResourceLimits,
    join_script_lines,
    status_matches,
)

__version__ = '0.3.0'

__all__ = [
    # 客户端（同步 / 异步）
    'ScnetClient',
    'ContainerHandle',
    'AsyncScnetClient',
    'AsyncContainerHandle',
    'ScnetClientBase',
    # 配置
    'ScnetConfig',
    'Endpoints',
    'Paths',
    'Timeouts',
    'StatusSets',
    'CODE_DEFAULTS',
    'ENV_OVERRIDES',
    'ENV_PREFIX',
    'CONFIG_ENV_VAR',
    'DEFAULT_CONFIG_NAMES',
    'PACKAGED_DEFAULTS_NAME',
    'load_yaml',
    'deep_merge',
    'env_layer',
    'packaged_defaults',
    'search_paths',
    'resolve_config_path',
    # 认证（同步 / 异步）
    'ScnetCredentials',
    'ClusterToken',
    'obtain_credentials',
    'obtain_credentials_async',
    'fetch_tokens',
    'fetch_tokens_async',
    'fetch_center',
    'fetch_center_async',
    'build_signature',
    'build_sign_message',
    'build_token_headers',
    'normalize_ai_url',
    'resolve_ai_url',
    'pick_ai_urls',
    'select_cluster',
    'DEFAULT_TOKEN_URL',
    'DEFAULT_CENTER_URL',
    # 模型
    'ContainerSpec',
    'ContainerInfo',
    'MountInfo',
    'PortInfo',
    'ResourceLimits',
    'join_script_lines',
    'status_matches',
    'ACCELERATOR_TYPES',
    'TASK_TYPES',
    'PROTOCOL_TYPES',
    'MOUNT_TYPES',
    'SCRIPT_ACTION_SCOPES',
    'DEFAULT_RUNNING_STATUSES',
    'DEFAULT_TERMINAL_STATUSES',
    # 共享逻辑
    'build_create_payload',
    'build_script_body',
    'normalize_ids',
    'parse_created_id',
    'parse_container_info',
    'parse_resource_limits',
    'wait_decision',
    'WAIT_READY',
    'WAIT_TERMINAL',
    'WAIT_PENDING',
    # 异常
    'ScnetError',
    'ScnetConfigError',
    'ScnetValidationError',
    'ScnetAuthError',
    'ScnetTransportError',
    'ScnetResponseError',
    'ScnetApiError',
    'ScnetStateError',
    'ScnetTimeoutError',
    'ERROR_MESSAGES',
    'describe_code',
    '__version__',
]
